---
- hosts: web
  tasks:
    - name: Create a User
      user:
        name: devops
        state: present
    - name: Install Apache Server
      apt:
        name: apache2
        state: present
    - name: Check Apache service is running 
      service:
        name: apache2
        state: started
    - name: Create a Directory
      file:
        name: /var/www/html/webapp
        mode: 777
        state: directory
    - name: Create a file
      file:
        name: /var/www/html/webapp/index.html
        state: touch
    - name: Copy Index.html File
      copy:
        src: /home/ubuntu/devop_notes/index.html
        dest: /var/www/html
    - name: Copy via Template module
      template:
        src: /home/ubuntu/devop_notes/index.html.j2
        dest: /var/www/html/webapp/index.html    
        

